id: P9559FC6D
initial_creation_type: ocr
source_metadata:
  volumes:
    53d9a9273d4b448c946119624d8a1ff7:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: རྟོག་པ་ལས་གསུངས་པའི་ལྷ་མོ་རིགས་བྱེད་མའི་སྒྲུབ་པའི་ཐབས།
      total_pages: 1648
      volume_number: 40
